services:
  backend:
    build:
      context: backend
      target: development
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    networks:
      - public
      - private
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/app
      # todo node_modules should be created with current user and group id, not root
    networks:
      - public
    depends_on:
      - backend

  db:
    image: postgres
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - ./backend/db/init.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - private
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db-data:

networks:
  public: 
    driver: bridge
  private:
