services:
  backend:
    build:
      context: backend
      target: development
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./backend:/app
    networks:
      - public
      - private
    depends_on:
      - db

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./frontend:/app
      # todo node_modules should be created with current user and group id, not root
    environment:
      VITE_API_URL: "http://localhost:3000/api/pets"
    networks:
      - public
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - private
    environment:
      - POSTGRES_DB=pets
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  public:
  private:

